name: Release and Publish

on:
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v6.3.0
        with:
          node-version: 22
          cache: npm

      - name: Remove Tag Prefix
        run: npm config set tag-version-prefix ""

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Run lint
        run: npm run lint

      - name: Format code
        run: npm run format:check

      - name: Build Project
        run: npm run build

      - name: Get Version
        id: get_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      #- name: Publish to npm
      #  env:
      #    NODE_AUTH_TOKEN: {{ secrets.NPM_TOKEN }}
      #  run: npm publish

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2.6.1
        with:
          tag_name: "${{ steps.get_version.outputs.version }}"
          name: "${{ steps.get_version.outputs.version }}"
          target_commitish: master
          body: |
            Automated release of version ${{ steps.get_version.outputs.version }}.
          files: |
            manifest.json
            main.js
            styles.css

      - name: Upload Plugin Files
        uses: actions/upload-artifact@v7.0.0
        with:
          name: insta-toc-${{ steps.get_version.outputs.version }}
          path: |
            manifest.json
            main.js
            styles.css
